### ISSUE TITLE
Logo?

### ISSUE THREAD

**Issue by ivoszz** [esemplastic/unis#1]
The logo you use is copyrighted work and is the logo of the UNIS company (http://www.unis.cz). I wonder if you have permission to use it.

**Comment by esemplastic** [comment]
The logo used by the unis.cz is an open-source **logo MIT licensed**, UNIS' logo too.
It would be better if people search in the web before throw accusations like these.

**Comment by esemplastic** [comment]
The logo used by the unis.cz is not protected by that company, search in the web for details. Anyway, the current project's logo will be changed soon if people like you try to contribute to open-source projects than throw accusations like these.

**Comment by esemplastic** [comment]
The logo used by the unis.cz is not protected by that company as far as I have read, search in the web for details. Anyway, the current project's logo will be changed soon if people like you try to contribute to open-source projects than throw accusations like these.

**Comment by esemplastic** [comment]
The 1-day logo which I choose is not protected by that company as far as I have read (search in the web for details). It would be better if people like you try to contribute to open-source projects than throw accusations like these. 

Anyway, I created a new logo by myself to stop any confusion and link to that company. 

It would be great to ask non-technical questions to the [chat](https://gitter.im/unis-go/Lobby) instead, github issues should be relative to users of this library and their problems or feature requests. It also looks bad to something like this to be the first issue by an open-source developer. Thank you @ivoszz .

**Comment by esemplastic** [comment]
Hello!

The 1-day logo which I choose is not protected by that company as far as I have read (search in the web for details). 


It would be great to ask non-technical questions to the [chat](https://gitter.im/unis-go/Lobby) instead, github issues should be relative to users of this library and their problems or feature requests. It also looks bad to something like this to be the first issue by an open-source developer. Thank you @ivoszz .

Update: 
Anyway, it was a good chance to create a new  logo (see below) by myself to stop any confusion and link to that company. Preview the new logo and share your thoughts with us!

![New Logo](https://raw.githubusercontent.com/esemplastic/unis/master/logo.png)
